# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: douyin.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64ouyin.proto\x12\x06\x64ouyin\"(\n\nPushHeader\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xb2\x01\n\tPushFrame\x12\r\n\x05seqid\x18\x01 \x01(\x04\x12\r\n\x05logid\x18\x02 \x01(\x04\x12\x0f\n\x07service\x18\x03 \x01(\x04\x12\x0e\n\x06method\x18\x04 \x01(\x04\x12\'\n\x0bheadersList\x18\x05 \x03(\x0b\x32\x12.douyin.PushHeader\x12\x17\n\x0fpayloadEncoding\x18\x06 \x01(\t\x12\x13\n\x0bpayloadType\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\"\xe4\x02\n\x08Response\x12%\n\x0cmessagesList\x18\x01 \x03(\x0b\x32\x0f.douyin.Message\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\x12\x15\n\rfetchInterval\x18\x03 \x01(\x04\x12\x0b\n\x03now\x18\x04 \x01(\x04\x12\x13\n\x0binternalExt\x18\x05 \x01(\t\x12\x11\n\tfetchType\x18\x06 \x01(\r\x12\x36\n\x0brouteParams\x18\x07 \x03(\x0b\x32!.douyin.Response.RouteParamsEntry\x12\x19\n\x11heartbeatDuration\x18\x08 \x01(\x04\x12\x0f\n\x07needAck\x18\t \x01(\x08\x12\x12\n\npushServer\x18\n \x01(\t\x12\x12\n\nliveCursor\x18\x0b \x01(\t\x12\x15\n\rhistoryNoMore\x18\x0c \x01(\x08\x1a\x32\n\x10RouteParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x01\n\x07Message\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\r\n\x05msgId\x18\x03 \x01(\x03\x12\x0f\n\x07msgType\x18\x04 \x01(\x05\x12\x0e\n\x06offset\x18\x05 \x01(\x03\x12\x15\n\rneedWrdsStore\x18\x06 \x01(\x08\x12\x13\n\x0bwrdsVersion\x18\x07 \x01(\x03\x12\x12\n\nwrdsSubKey\x18\x08 \x01(\tb\x06proto3')



_PUSHHEADER = DESCRIPTOR.message_types_by_name['PushHeader']
_PUSHFRAME = DESCRIPTOR.message_types_by_name['PushFrame']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_RESPONSE_ROUTEPARAMSENTRY = _RESPONSE.nested_types_by_name['RouteParamsEntry']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
PushHeader = _reflection.GeneratedProtocolMessageType('PushHeader', (_message.Message,), {
  'DESCRIPTOR' : _PUSHHEADER,
  '__module__' : 'douyin_pb2'
  # @@protoc_insertion_point(class_scope:douyin.PushHeader)
  })
_sym_db.RegisterMessage(PushHeader)

PushFrame = _reflection.GeneratedProtocolMessageType('PushFrame', (_message.Message,), {
  'DESCRIPTOR' : _PUSHFRAME,
  '__module__' : 'douyin_pb2'
  # @@protoc_insertion_point(class_scope:douyin.PushFrame)
  })
_sym_db.RegisterMessage(PushFrame)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'RouteParamsEntry' : _reflection.GeneratedProtocolMessageType('RouteParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_ROUTEPARAMSENTRY,
    '__module__' : 'douyin_pb2'
    # @@protoc_insertion_point(class_scope:douyin.Response.RouteParamsEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'douyin_pb2'
  # @@protoc_insertion_point(class_scope:douyin.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.RouteParamsEntry)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'douyin_pb2'
  # @@protoc_insertion_point(class_scope:douyin.Message)
  })
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE_ROUTEPARAMSENTRY._options = None
  _RESPONSE_ROUTEPARAMSENTRY._serialized_options = b'8\001'
  _PUSHHEADER._serialized_start=24
  _PUSHHEADER._serialized_end=64
  _PUSHFRAME._serialized_start=67
  _PUSHFRAME._serialized_end=245
  _RESPONSE._serialized_start=248
  _RESPONSE._serialized_end=604
  _RESPONSE_ROUTEPARAMSENTRY._serialized_start=554
  _RESPONSE_ROUTEPARAMSENTRY._serialized_end=604
  _MESSAGE._serialized_start=607
  _MESSAGE._serialized_end=761
# @@protoc_insertion_point(module_scope)
